spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://g9-postgres.postgres.database.azure.com:5432/postgres
    username: g9_admin
    password: Giscina2021
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    fer.gis.backend.web.rest: DEBUG


security:
  master:
    password: "HarDPassWorD"
#server:
#  servlet:
#    context-path: /gisg9